# Generated by Django 5.1.5 on 2025-03-06 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_view', models.BooleanField(default=True)),
                ('is_download', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fileaccessroles',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_link', models.CharField(max_length=255, unique=True)),
                ('created_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='UserFileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField()),
                ('updated_time', models.DateField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.fileaccessroles')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userfileaccess',
            },
        ),
    ]
