# Generated by Django 5.1.5 on 2025-03-16 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfileaccess',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userfileaccess',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
    ]
