# Generated by Django 5.1.5 on 2025-03-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_files_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
