# Generated by Django 5.1.5 on 2025-03-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_alter_files_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='is_delete',
        ),
    ]
